# Generated by Django 3.2.3 on 2021-06-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choroba',
            options={'verbose_name_plural': 'Choroba'},
        ),
        migrations.AlterModelOptions(
            name='dyzur',
            options={'verbose_name_plural': 'Dyzur'},
        ),
        migrations.AlterModelOptions(
            name='lek',
            options={'verbose_name_plural': 'Lek'},
        ),
        migrations.AlterModelOptions(
            name='lekarz',
            options={'verbose_name_plural': 'Lekarz'},
        ),
        migrations.AlterModelOptions(
            name='objaw',
            options={'verbose_name_plural': 'Objaw'},
        ),
        migrations.AlterModelOptions(
            name='pacjent',
            options={'verbose_name_plural': 'Pacjent'},
        ),
        migrations.AlterModelOptions(
            name='recepta',
            options={'verbose_name_plural': 'Recepta'},
        ),
        migrations.AlterModelOptions(
            name='wizyta',
            options={'verbose_name_plural': 'Wizyta'},
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='idChoroba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.choroba'),
        ),
    ]
