# Generated by Django 3.2.3 on 2021-06-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_alter_lekarz_specjalizacja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choroba',
            name='opis',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='recepta',
            name='dataWaznosci',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='idRecepta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='start.recepta'),
        ),
    ]
