# Generated by Django 3.2.3 on 2021-06-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_auto_20210604_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choroba',
            name='idObjaw',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='start.objaw'),
        ),
    ]
