# Generated by Django 3.2.3 on 2021-06-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_alter_choroba_idobjaw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyzur',
            name='czasRozpoczecia',
        ),
        migrations.RemoveField(
            model_name='dyzur',
            name='czasZakonczenia',
        ),
        migrations.AddField(
            model_name='dyzur',
            name='dzienRozpoczecia',
            field=models.DateField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyzur',
            name='dzienZakonczenia',
            field=models.DateField(default=2011),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyzur',
            name='godzinaRozpoczecia',
            field=models.TimeField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyzur',
            name='godzinaZakonczenia',
            field=models.TimeField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lek',
            name='refundacja',
            field=models.SmallIntegerField(default=0),
        ),
    ]
