# Generated by Django 3.2.3 on 2021-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_auto_20210604_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyzur',
            name='dzienRozpoczecia',
            field=models.DateField(),
        ),
    ]
